apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: solar-app

resources: 
  - https://github.com/sanjeevk9/argocd/apps/solar-system?ref=v1.0.0

patchesStrategicMerge:
  - version.yaml
  